// <auto-generated />
using System;
using System.Net;
using GeoIP.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GeoIP.Server.Data.Migrations
{
    [DbContext(typeof(GeoIpDbContext))]
    [Migration("20200118221423_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GeoIP.Shared.Models.Blocks", b =>
                {
                    b.Property<ValueTuple<IPAddress, int>>("Network")
                        .HasColumnName("network")
                        .HasColumnType("cidr");

                    b.Property<short?>("AccuracyRadius")
                        .HasColumnName("accuracy_radius")
                        .HasColumnType("smallint");

                    b.Property<short?>("GeonameId")
                        .IsRequired()
                        .HasColumnName("geoname_id")
                        .HasColumnType("smallint");

                    b.Property<bool?>("IsAnonymousProxy")
                        .HasColumnName("is_anonymous_proxy")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSatelliteProvider")
                        .HasColumnName("is_satellite_provider")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasColumnName("latitude")
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnName("longitude")
                        .HasColumnType("numeric(7,4)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnName("postal_code")
                        .HasColumnType("text");

                    b.Property<short?>("RegisteredCountryGeonameId")
                        .HasColumnName("registered_country_geoname_id")
                        .HasColumnType("smallint");

                    b.Property<short?>("RepresentedCountryGeonameId")
                        .HasColumnName("represented_country_geoname_id")
                        .HasColumnType("smallint");

                    b.HasKey("Network")
                        .HasName("blocks_pkey");

                    b.HasIndex("GeonameId");

                    b.ToTable("blocks");
                });

            modelBuilder.Entity("GeoIP.Shared.Models.Locations", b =>
                {
                    b.Property<short>("GeonameId")
                        .HasColumnName("geoname_id")
                        .HasColumnType("smallint");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnName("city_name")
                        .HasColumnType("text");

                    b.Property<string>("ContinentCode")
                        .IsRequired()
                        .HasColumnName("continent_code")
                        .HasColumnType("character varying(2)")
                        .HasMaxLength(2);

                    b.Property<string>("ContinentName")
                        .IsRequired()
                        .HasColumnName("continent_name")
                        .HasColumnType("text");

                    b.Property<string>("CountryIsoCode")
                        .IsRequired()
                        .HasColumnName("country_iso_code")
                        .HasColumnType("character varying(2)")
                        .HasMaxLength(2);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnName("country_name")
                        .HasColumnType("text");

                    b.Property<bool?>("IsInEuropeanUnion")
                        .HasColumnName("is_in_european_union")
                        .HasColumnType("boolean");

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasColumnName("locale_code")
                        .HasColumnType("character varying(2)")
                        .HasMaxLength(2);

                    b.Property<short?>("MetroCode")
                        .HasColumnName("metro_code")
                        .HasColumnType("smallint");

                    b.Property<string>("Subdivision1IsoCode")
                        .IsRequired()
                        .HasColumnName("subdivision_1_iso_code")
                        .HasColumnType("character varying(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Subdivision1Name")
                        .IsRequired()
                        .HasColumnName("subdivision_1_name")
                        .HasColumnType("text");

                    b.Property<string>("Subdivision2IsoCode")
                        .IsRequired()
                        .HasColumnName("subdivision_2_iso_code")
                        .HasColumnType("character varying(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Subdivision2Name")
                        .IsRequired()
                        .HasColumnName("subdivision_2_name")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnName("time_zone")
                        .HasColumnType("text");

                    b.HasKey("GeonameId")
                        .HasName("locations_pkey");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("GeoIP.Shared.Models.Blocks", b =>
                {
                    b.HasOne("GeoIP.Shared.Models.Locations", "Geoname")
                        .WithMany("Blocks")
                        .HasForeignKey("GeonameId")
                        .HasConstraintName("blocks_geoname_id_fkey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
